export const POPULAR_DESTINATIONS = [
  "Turkey",
  "Greece",
  "Egypt",
  "Dubai",
  "Morocco",
  "Portugal",
  "Spain",
  "Thailand",
  "Tunisia",
];

export const ALL_DESTINATIONS = [
  "Albania",
  "Amsterdam",
  "Budapest",
  "Canary Islands",
  "Cape Verde",
  "Caribbean",
  "Croatia",
  "Cyprus",
  "Dominican Republic",
  "Dubai",
  "Egypt",
  "Greece",
  "Ireland",
  "Italy",
  "Las Vegas",
  "Maldives",
  "Malta",
  "Mexico",
  "Morocco",
  "New York",
  "Paris",
  "Portugal",
  "Qatar",
  "Spain",
  "Thailand",
  "Tunisia",
  "Turkey",
  "United Kingdom",
];

export const DESTINATION_FLAGS: Record<string, string> = {
  Turkey: "🇹🇷",
  Greece: "🇬🇷",
  Egypt: "🇪🇬",
  Dubai: "🇦🇪",
  Morocco: "🇲🇦",
  Portugal: "🇵🇹",
  Spain: "🇪🇸",
  Thailand: "🇹🇭",
  Tunisia: "🇹🇳",
  Albania: "🇦🇱",
  Amsterdam: "🇳🇱",
  "Balearic Islands": "🇪🇸",
  Budapest: "🇭🇺",
  "Canary Islands": "🇪🇸",
  "Cape Verde": "🇨🇻",
  Caribbean: "🏝️",
  Croatia: "🇭🇷",
  Cyprus: "🇨🇾",
  "Dominican Republic": "🇩🇴",
  Ireland: "🇮🇪",
  Italy: "🇮🇹",
  "Las Vegas": "🇺🇸",
  Maldives: "🇲🇻",
  Malta: "🇲🇹",
  Mexico: "🇲🇽",
  "New York": "🇺🇸",
  Paris: "🇫🇷",
  Qatar: "🇶🇦",
  "United States of America": "🇺🇸",
  "United Kingdom": "🇬🇧",
};

export const DESTINATION_CODES: Record<string, string> = {
  Turkey: "tr",
  Greece: "gr",
  Egypt: "eg",
  Dubai: "ae",
  Morocco: "ma",
  Portugal: "pt",
  Spain: "es",
  Thailand: "th",
  Tunisia: "tn",
  Albania: "al",
  Amsterdam: "nl",
  "Balearic Islands": "es",
  Budapest: "hu",
  "Canary Islands": "es",
  "Cape Verde": "cv",
  Caribbean: "un", // Generic or union
  Croatia: "hr",
  Cyprus: "cy",
  "Dominican Republic": "do",
  Ireland: "ie",
  Italy: "it",
  "Las Vegas": "us",
  Maldives: "mv",
  Malta: "mt",
  Mexico: "mx",
  "New York": "us",
  Paris: "fr",
  Qatar: "qa",
  "United States of America": "us",
  "United Kingdom": "gb",
};


export const AIRPORTS = [
  "Any Airport",
  "Any London",
  "Any Midlands",
  "Any North East",
  "Any North West",
  "Any South West",
  "Any Scotland",
  "Any Northern Ireland",
];

export const MONTHS = [
  "Any",
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December",
];
